language: node_js
node_js:
  - "0.11"
install:
 - npm install jshint -g
 - npm install PrettyCSS -g
script:
 - jshint main.js
 - prettycss --ignore suggest-relative-unit:px main.css >/dev/null
branches:
  only:
    - master
    - gh-pages
